# Generated by Django 5.0.6 on 2024-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('vehicle_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(default='2c3ca6c668', max_length=10, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('response_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(default='5ce05b640a', max_length=10, unique=True)),
                ('intersection', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('vehicles_detected', models.IntegerField()),
                ('traffic_light_status', models.CharField(max_length=10)),
            ],
        ),
    ]
